### ISSUE TITLE
can't not resolve 'BenchmarkMeasure' function in benchmark subproject

### ISSUE THREAD

**Issue by xw0078** [helgeho/ArchiveSpark#6]
Hi, 

I am trying to repeat your benchmark subproject on ArchiveSpark. 
I found 'BenchmarkMeasure' function is properly missing. 

And there's one small mistake in Benchmark.scala:
`package de1.l3s.archivesparkb.benchmarking`
which should be
`package de.l3s.archivespark.benchmarking`

Best,
Cyrus

**Comment by helgeho** [comment]
Hi Cyrus,

Thanks for the hint, this is really strange, I have no clue how that happened.

I now recovered the missing `BenchmarkMeasure` from this commit https://github.com/helgeho/ArchiveSpark/tree/2598eb870a661c6cd28059fe799f6c3143387c53
And fixed package name of `Benchmark`.

It might be still difficult to run those benchmarks though, as all involved tools, i.e., *ArchiveSpark*, *HBase* and *WarcBase/AUT*, have changed a lot since we wrote this code and we do not maintain it actively. Please read [this README](https://github.com/helgeho/ArchiveSpark/blob/master/subprojects/benchmarking/Readme.md) for more details.

Please keep us posted on your benchmarks and please share your results, thanks!

Best,
Helge

**Comment by xw0078** [comment]
Hi Helge, 

Many thanks for providing the information. The old commit actually solves many of issues I encountered. And I am using this specific commit to test things. Currently, I am  blocked by an error that seem to be very trivial when I try to run the program:
`ERROR TableInputFormat - java.io.IOException: maxStamp is smaller than minStamp`
I haven't found any good information about this issue. Wondering if you have encountered this.

Best,
Cyrus

The full error log is here:

ERROR TableInputFormat - java.io.IOException: maxStamp is smaller than minStamp
	at org.apache.hadoop.hbase.io.TimeRange.<init>(TimeRange.java:88)
	at org.apache.hadoop.hbase.client.Scan.setTimeRange(Scan.java:330)
	at org.apache.hadoop.hbase.mapreduce.TableInputFormat.setConf(TableInputFormat.java:153)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:120)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:91)
	at org.apache.spark.rdd.ShuffledRDD.getDependencies(ShuffledRDD.scala:80)
	at org.apache.spark.rdd.RDD$$anonfun$dependencies$2.apply(RDD.scala:226)
	at org.apache.spark.rdd.RDD$$anonfun$dependencies$2.apply(RDD.scala:224)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.dependencies(RDD.scala:224)
	at org.apache.spark.rdd.ShuffledRDD.getPreferredLocations(ShuffledRDD.scala:91)
	at org.apache.spark.rdd.RDD$$anonfun$preferredLocations$2.apply(RDD.scala:257)
	at org.apache.spark.rdd.RDD$$anonfun$preferredLocations$2.apply(RDD.scala:257)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.preferredLocations(RDD.scala:256)
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$getPreferredLocsInternal(DAGScheduler.scala:1573)
	at org.apache.spark.scheduler.DAGScheduler.getPreferredLocs(DAGScheduler.scala:1547)
	at org.apache.spark.SparkContext.getPreferredLocs(SparkContext.scala:1628)
	at org.apache.spark.rdd.PartitionCoalescer.currPrefLocs(CoalescedRDD.scala:178)
	at org.apache.spark.rdd.PartitionCoalescer$LocationIterator$$anonfun$6$$anonfun$apply$2.apply(CoalescedRDD.scala:195)
	at org.apache.spark.rdd.PartitionCoalescer$LocationIterator$$anonfun$6$$anonfun$apply$2.apply(CoalescedRDD.scala:194)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:350)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:350)
	at org.apache.spark.rdd.PartitionCoalescer$LocationIterator.<init>(CoalescedRDD.scala:189)
	at org.apache.spark.rdd.PartitionCoalescer.setupGroups(CoalescedRDD.scala:240)
	at org.apache.spark.rdd.PartitionCoalescer.run(CoalescedRDD.scala:341)
	at org.apache.spark.rdd.CoalescedRDD.getPartitions(CoalescedRDD.scala:87)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:91)
	at org.apache.spark.rdd.ShuffledRDD.getDependencies(ShuffledRDD.scala:80)
	at org.apache.spark.rdd.RDD$$anonfun$dependencies$2.apply(RDD.scala:226)
	at org.apache.spark.rdd.RDD$$anonfun$dependencies$2.apply(RDD.scala:224)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.dependencies(RDD.scala:224)
	at org.apache.spark.scheduler.DAGScheduler.visit$1(DAGScheduler.scala:386)
	at org.apache.spark.scheduler.DAGScheduler.getParentStages(DAGScheduler.scala:398)
	at org.apache.spark.scheduler.DAGScheduler.getParentStagesAndId(DAGScheduler.scala:299)
	at org.apache.spark.scheduler.DAGScheduler.newResultStage(DAGScheduler.scala:334)
	at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:837)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1635)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1627)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1616)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)

ERROR TableInputFormat - java.io.IOException: maxStamp is smaller than minStamp
	at org.apache.hadoop.hbase.io.TimeRange.<init>(TimeRange.java:88)
	at org.apache.hadoop.hbase.client.Scan.setTimeRange(Scan.java:330)
	at org.apache.hadoop.hbase.mapreduce.TableInputFormat.setConf(TableInputFormat.java:153)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:161)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:133)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:65)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by helgeho** [comment]
I am glad that it is almost working for you now. Regarding this particular exception, I really have no idea. It is definitely something HBase related, kind of sounds like the captures of a URL are inserted or queried in reserve order (latest capture first). This should not be the case if you used the WarcBase tools to ingest your data into HBase and the provided benchmark jobs to run the queries, I never encountered this. Did you make sure to change the year and month in `runOneMonthLatestOnline` to match your dataset?
